# Generated by Django 3.2.5 on 2021-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(max_length=6)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('aadhar_number', models.IntegerField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('current_location', models.CharField(max_length=255)),
                ('skill', models.CharField(choices=[('ELECTRICIAN', 'ELECTRICIAN'), ('PLUMBER', 'PLUMBER'), ('LABOUR', 'LABOUR'), ('DRIVER', 'DRIVER'), ('MAID', 'MAID'), ('SECURITY GUARD', 'SECURITY GUARD'), ('COOK', 'COOK'), ('MECHANIC', 'MECHANIC'), ('PEON', 'PEON'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
