# Generated by Django 3.2.5 on 2021-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='aadhar_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labour',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labour',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labour',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
