# Generated by Django 3.2.5 on 2021-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_auto_20210706_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='aadhar_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='contact_number',
            field=models.IntegerField(unique=True),
        ),
    ]
