# Generated by Django 3.2.5 on 2021-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0004_alter_labour_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='aadhar_number',
            field=models.IntegerField(unique=True),
        ),
    ]
