# Generated by Django 3.2.5 on 2021-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0006_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('pune', 'pune'), ('banglore', 'banglore'), ('mumbai', 'mumbai'), ('delhi', 'delhi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labour',
            name='current_location',
            field=models.CharField(choices=[('pune', 'pune'), ('banglore', 'banglore'), ('mumbai', 'mumbai'), ('delhi', 'delhi')], max_length=20),
        ),
    ]
