# Generated by Django 3.2.5 on 2021-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0007_auto_20210720_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer_contact',
            field=models.BigIntegerField(unique=True),
        ),
    ]
